### ISSUE TITLE
ytoj is not handling nullables well

### ISSUE THREAD

**Issue by zoka123** [tromgy/swagger-yaml-to-json-schema#4]
First of all, great job with the library, it helps a lot 👍 
If I understood correctly, JSON Schema does not support the `nullable` keyword.

## References:
- https://github.com/mikunn/openapi-schema-to-json-schema: "deletes nullable and adds "null" to type array if nullable is true"
- https://json-schema.org/understanding-json-schema/reference/null.html

## Expected:
Schema for property name:
```
name:
  type: string
  nullable: true
```

Should be converted to:
```
"name": {
  "type": ["string", "null"]
}
```

## Actual:
```
"name": {
  "type": "string",
  "nullable": false
}
```

**Comment by tromgy** [comment]
Thank you for bringing this to my attention. It is now fixed in version 1.1.3
